### ISSUE TITLE
Mac Visual Studio Preview unable to build ...

### ISSUE THREAD

**Issue by spillsthrills** [cartermp/fs5preview#6]
Perhaps Mac Visual Studio Preview is not ready however, I can create a new .net 5 console app which probably means I may missed something getting this setup correctly.

/fs5preview/fsharp/fs5preview.fsproj : warning NU1605: Detected package downgrade: FSharp.Core from 4.7.0 to 4.5.2. Reference the package directly from the project to select a different version. 
fs5preview/fsharp/fs5preview.fsproj : warning NU1605:  fs5preview -> FSharp.SystemTextJson 0.12.12 -> FSharp.Core (>= 4.7.0) 
/fs5preview/fsharp/fs5preview.fsproj : warning NU1605:  fs5preview -> FSharp.Core (>= 4.5.2)
/fs5preview/fsharp/InterpolatedStrings.fs(7,13): error FS1160: This token is reserved for future use
/fs5preview/fsharp/InterpolatedStrings.fs(7,13): error FS0010: Unexpected whitespace in binding. Expected incomplete structured construct at or before this point or other token.
/fs5preview/fsharp/InterpolatedStrings.fs(19,46): error FS0514: End of file in string begun at or before here
/fs5preview/fsharp/Applicatives.fs(23,13): error FS1141: Identifiers followed by '!' are reserved for future use
/fs5preview/fsharp/Applicatives.fs(24,13): error FS1141: Identifiers followed by '!' are reserved for future use
/fs5preview/fsharp/Applicatives.fs(13,13): error FS0010: Unexpected symbol '.' in member definition. Expected 'with', '=' or other token.
/fs5preview/fsharp/OpenTypeDeclarations.fs(4,6): error FS0010: Unexpected keyword 'type' in open declaration. Expected identifier, 'global' or other token.
//fs5preview/fsharp/OpenTypeDeclarations.fs(14,6): error FS0010: Unexpected keyword 'type' in open declaration. Expected identifier, 'global' or other token.
/fs5preview/fsharp/Nameof.fs(11,13): error FS0010: Unexpected symbol '.' in member definition. Expected 'with', '=' or other token.
/fs5preview/fsharp/Slices.fs(22,19): error FS0010: Unexpected symbol '|' in expression
/fs5preview/fsharp/Slices.fs(22,18): error FS0604: Unmatched '{'
/fs5preview/fsharp/Slices.fs(59,22): error FS0010: Unexpected infix operator in expression
/fs5preview/fsharp/Slices.fs(59,21): error FS0598: Unmatched '['
/fs5preview/fsharp/Slices.fs(69,19): error FS0010: Unexpected infix operator in expression
/fs5preview/fsharp/Slices.fs(69,18): error FS0598: Unmatched '['
/fs5preview/fsharp/Slices.fs(72,1): error FS0010: Incomplete structured construct at or before this point in implementation file
/fs5preview/fsharp/DefaultInterfaceImplementationsInterop.fs(7,13): error FS0010: Unexpected symbol '.' in member definition. Expected 'with', '=' or other token.

**Comment by cartermp** [comment]
Yes, VSMac 8.8 Preview is not able to support F# 5 at the moment because it requires Mono to do builds in the IDE. We have F# 5 support in Mono coming and support for that in VSMac will likely be in the release after 8.8.
